// <auto-generated />
namespace AngularAndRequireJS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ticketimportantnotneeded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ticketimportantnotneeded));
        
        string IMigrationMetadata.Id
        {
            get { return "201507220258252_ticket-important-not-needed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
